In [1]:
#문제1
import numpy as np


arr2 = np.array([[1,2,3],[4,5,6]])
arr2 = arr2.flatten()*2
arr2

array([ 2,  4,  6,  8, 10, 12])

In [2]:
print(arr2)

[ 2  4  6  8 10 12]


In [3]:
#문제3
import numpy as np

arr = np.arange(5,31,5)
arr

array([ 5, 10, 15, 20, 25, 30])

In [11]:
#문제4
arr1 = np.zeros([2,3], dtype=int)
print(arr1)
print(arr1.shape)
print(arr1.ndim)
print(arr1.dtype)
print(arr1.size)

[[0 0 0]
 [0 0 0]]
(2, 3)
2
int32
6


In [13]:
#문제5
arr1 = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr1)
print(arr1[1])
print(arr1[2,2])
print(arr1[1:3])
print(arr1[arr1 <= 5])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[4 5 6]
9
[[4 5 6]
 [7 8 9]]
[1 2 3 4 5]
